[workspace]
members = ["sss"]

resolver = "2"

[workspace.package]
name = "dkg-from-scratch"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
bls12_381 = "0.8.0"
ff = "0.13.1"
rand = "0.8"
rand_core = "0.9.5"
