[workspace]
members = ["sss", "vss"]

resolver = "2"

[workspace.package]
name = "dkg-from-scratch"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
sss = { version = "0.1.0", path = "sss" }
bls12_381 = "0.8.0"
ff = "0.13.1"
group = "0.13.0"
rand = "0.8"
rand_core = "0.9.5"
