[package]
name = "sss"
description = "Shamir secret sharing"
version = "0.1.0"
edition = "2024"

[dependencies]
bls12_381 = { workspace = true }
ff = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
