[package]
name = "sss"
description = "Shamir secret sharing "
version.workspace = true
edition.workspace = true

[dependencies]
bls12_381 = { workspace = true }
ff = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
